### ISSUE TITLE
Exception: NameError: uninitialized constant Chef::REST

### ISSUE THREAD

**Issue by e100** [zuazo/chef-encrypted-attributes#5]
Upgraded ChefDK and now knife encrypted attribute give me an error.
Chef Development Kit Version: 0.15.15
chef-client version: 12.11.18

Line 378 /lib/chef/encrypted_attribute/search_helper.rb is the problem.

Chef::REST is depreciated, simply replacing it with Chef::ServerAPI resolved the error.

**Comment by zuazo** [comment]
Thanks for the report @e100. Please, could you make a PR for it?
